//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentacionSOAP.ProxyUsuarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/LogicaFinanciera")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PresentacionSOAP.ProxyUsuarios.Movimiento[] MovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal id_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal numero_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal saldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_documentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PresentacionSOAP.ProxyUsuarios.Movimiento[] Movimiento {
            get {
                return this.MovimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.MovimientoField, value) != true)) {
                    this.MovimientoField = value;
                    this.RaisePropertyChanged("Movimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                if ((this.id_usuarioField.Equals(value) != true)) {
                    this.id_usuarioField = value;
                    this.RaisePropertyChanged("id_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal numero_documento {
            get {
                return this.numero_documentoField;
            }
            set {
                if ((this.numero_documentoField.Equals(value) != true)) {
                    this.numero_documentoField = value;
                    this.RaisePropertyChanged("numero_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal saldo {
            get {
                return this.saldoField;
            }
            set {
                if ((this.saldoField.Equals(value) != true)) {
                    this.saldoField = value;
                    this.RaisePropertyChanged("saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_documento {
            get {
                return this.tipo_documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_documentoField, value) != true)) {
                    this.tipo_documentoField = value;
                    this.RaisePropertyChanged("tipo_documento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movimiento", Namespace="http://schemas.datacontract.org/2004/07/LogicaFinanciera")]
    [System.SerializableAttribute()]
    public partial class Movimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PresentacionSOAP.ProxyUsuarios.Usuario UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal id_movimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal id_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> num_aprovacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PresentacionSOAP.ProxyUsuarios.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal id_movimiento {
            get {
                return this.id_movimientoField;
            }
            set {
                if ((this.id_movimientoField.Equals(value) != true)) {
                    this.id_movimientoField = value;
                    this.RaisePropertyChanged("id_movimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                if ((this.id_usuarioField.Equals(value) != true)) {
                    this.id_usuarioField = value;
                    this.RaisePropertyChanged("id_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> num_aprovacion {
            get {
                return this.num_aprovacionField;
            }
            set {
                if ((this.num_aprovacionField.Equals(value) != true)) {
                    this.num_aprovacionField = value;
                    this.RaisePropertyChanged("num_aprovacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal valor {
            get {
                return this.valorField;
            }
            set {
                if ((this.valorField.Equals(value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUsuarios.IWSUsuarios")]
    public interface IWSUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/DoWork", ReplyAction="http://tempuri.org/IWSUsuarios/DoWorkResponse")]
        PresentacionSOAP.ProxyUsuarios.Usuario[] DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/DoWork", ReplyAction="http://tempuri.org/IWSUsuarios/DoWorkResponse")]
        System.Threading.Tasks.Task<PresentacionSOAP.ProxyUsuarios.Usuario[]> DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/GetAllUsuario", ReplyAction="http://tempuri.org/IWSUsuarios/GetAllUsuarioResponse")]
        PresentacionSOAP.ProxyUsuarios.Usuario[] GetAllUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/GetAllUsuario", ReplyAction="http://tempuri.org/IWSUsuarios/GetAllUsuarioResponse")]
        System.Threading.Tasks.Task<PresentacionSOAP.ProxyUsuarios.Usuario[]> GetAllUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/AddUsuario", ReplyAction="http://tempuri.org/IWSUsuarios/AddUsuarioResponse")]
        int AddUsuario(PresentacionSOAP.ProxyUsuarios.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/AddUsuario", ReplyAction="http://tempuri.org/IWSUsuarios/AddUsuarioResponse")]
        System.Threading.Tasks.Task<int> AddUsuarioAsync(PresentacionSOAP.ProxyUsuarios.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/GetAllUsuarioById", ReplyAction="http://tempuri.org/IWSUsuarios/GetAllUsuarioByIdResponse")]
        PresentacionSOAP.ProxyUsuarios.Usuario GetAllUsuarioById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/GetAllUsuarioById", ReplyAction="http://tempuri.org/IWSUsuarios/GetAllUsuarioByIdResponse")]
        System.Threading.Tasks.Task<PresentacionSOAP.ProxyUsuarios.Usuario> GetAllUsuarioByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/UpdateUsuario", ReplyAction="http://tempuri.org/IWSUsuarios/UpdateUsuarioResponse")]
        int UpdateUsuario(PresentacionSOAP.ProxyUsuarios.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/UpdateUsuario", ReplyAction="http://tempuri.org/IWSUsuarios/UpdateUsuarioResponse")]
        System.Threading.Tasks.Task<int> UpdateUsuarioAsync(PresentacionSOAP.ProxyUsuarios.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/DeleteUsuarioById", ReplyAction="http://tempuri.org/IWSUsuarios/DeleteUsuarioByIdResponse")]
        int DeleteUsuarioById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUsuarios/DeleteUsuarioById", ReplyAction="http://tempuri.org/IWSUsuarios/DeleteUsuarioByIdResponse")]
        System.Threading.Tasks.Task<int> DeleteUsuarioByIdAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSUsuariosChannel : PresentacionSOAP.ProxyUsuarios.IWSUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSUsuariosClient : System.ServiceModel.ClientBase<PresentacionSOAP.ProxyUsuarios.IWSUsuarios>, PresentacionSOAP.ProxyUsuarios.IWSUsuarios {
        
        public WSUsuariosClient() {
        }
        
        public WSUsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSUsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSUsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSUsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PresentacionSOAP.ProxyUsuarios.Usuario[] DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<PresentacionSOAP.ProxyUsuarios.Usuario[]> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public PresentacionSOAP.ProxyUsuarios.Usuario[] GetAllUsuario() {
            return base.Channel.GetAllUsuario();
        }
        
        public System.Threading.Tasks.Task<PresentacionSOAP.ProxyUsuarios.Usuario[]> GetAllUsuarioAsync() {
            return base.Channel.GetAllUsuarioAsync();
        }
        
        public int AddUsuario(PresentacionSOAP.ProxyUsuarios.Usuario usuario) {
            return base.Channel.AddUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<int> AddUsuarioAsync(PresentacionSOAP.ProxyUsuarios.Usuario usuario) {
            return base.Channel.AddUsuarioAsync(usuario);
        }
        
        public PresentacionSOAP.ProxyUsuarios.Usuario GetAllUsuarioById(int id) {
            return base.Channel.GetAllUsuarioById(id);
        }
        
        public System.Threading.Tasks.Task<PresentacionSOAP.ProxyUsuarios.Usuario> GetAllUsuarioByIdAsync(int id) {
            return base.Channel.GetAllUsuarioByIdAsync(id);
        }
        
        public int UpdateUsuario(PresentacionSOAP.ProxyUsuarios.Usuario usuario) {
            return base.Channel.UpdateUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<int> UpdateUsuarioAsync(PresentacionSOAP.ProxyUsuarios.Usuario usuario) {
            return base.Channel.UpdateUsuarioAsync(usuario);
        }
        
        public int DeleteUsuarioById(int Id) {
            return base.Channel.DeleteUsuarioById(Id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteUsuarioByIdAsync(int Id) {
            return base.Channel.DeleteUsuarioByIdAsync(Id);
        }
    }
}
